# Generated by Django 3.0.5 on 2020-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='', upload_to='Ecommerce/images')),
                ('image2', models.ImageField(default='', upload_to='Ecommerce/images')),
            ],
        ),
    ]
