# Generated by Django 3.0.5 on 2020-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='image1',
            field=models.ImageField(default='', upload_to='Root/images'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='image2',
            field=models.ImageField(default='', upload_to='Root/images'),
        ),
    ]
